# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Real General Practice
email: info@code4health.org
description: > # this means to ignore newlines until "baseurl:"
  AN INNOVATIVE APPROACH TO IMPROVING CONSULTING SKILLS FOR GP'S, GP REGISTRARS AND MEDICAL STUDENTS
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://realgp.github.io/" # the base hostname & protocol for your site
twitter_username: code4health
github_username:  Apperta

collections:
 - patients
 - clinicians

gems:
  - jekyll-archives

# Build settings
markdown: kramdown
exclude: ["README.md"]
include: ['_pages']

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
